# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

    app.service.life_cycle.cycle_handler:
        class: AppBundle\Service\LifeCycle\CycleHandler

    app.service.life_cycle.cycle_loop:
        class: AppBundle\Service\LifeCycle\CycleLoop
        arguments:
            - @app.service.shell_command_repository
            - @app.service.life_cycle.cycle_handler

    app.service.shell_command_repository:
        class: %app.service.shell_command_repository%

    app.service.terminal_drawer:
        class: AppBundle\Service\Terminal\LowLevel\TerminalDrawer

    app.service.screen_explorer:
        class: AppBundle\Service\ScreenExplorer
        arguments:
            - @app.service.shell_command_repository

    app.service.screen_drawer:
        class: AppBundle\Service\ScreenDrawer
        arguments:
            - @app.service.shell_command_repository
            - @app.service.terminal_drawer